### ISSUE TITLE
Add a signup and login page to your project 

### ISSUE THREAD

**Issue by manya1632** [SaranshBangar/Daneizo#1]
I will add a sign up and login page for the website matching the color theme and fonts. I will also try to embed some cool animations.

Checklist
 ✔️I have read the Contributing Guidelines
 ✔️I have read the Code Of Conduct
 ✔️The changes don't break the code

Assign the task to me @SaranshBangar

**Comment by SaranshBangar** [comment]
@manya1632 Alright, you can start working on it, but share some pictures of the work that you will do before raising a PR.

Moreover, make sure to follow the proper file structure

**Comment by manya1632** [comment]
Sir, there will be some delay in completing this task due to my exams. So, I am expecting a delay of about 8 days . I want to do this task but if there's any urgency feel free to assign this task to someone else. 
Thank you.

**Comment by SaranshBangar** [comment]
@manya1632 
1. No worries, please take your time
2. No need for 'sir' please, it makes me feel old 😅

**Comment by manya1632** [comment]
Haha, Thanks !

**Comment by SaranshBangar** [comment]
I am really sorry @iamsohelx, this issue is already assigned, you can take over some other issue or raise an issue of your own

**Comment by iamsohelx** [comment]
@SaranshBangar No problem brother.

**Comment by aasiflm10** [comment]
@SaranshBangar can i work on this issue. Will do it by tomorrow.

**Comment by SaranshBangar** [comment]
I am really sorry @aasiflm10, this issue is already assigned, you can take over some other issue or raise an issue of your own

**Comment by aasiflm10** [comment]
No worries @SaranshBangar . If for some reason the asignee is not able to complete this issue, i would like to work on it.

**Comment by SaranshBangar** [comment]
> No worries @SaranshBangar . If for some reason the asignee is not able to complete this issue, i would like to work on it.

Sure 👍🏼

**Comment by Ameerjafar** [comment]
@SaranshBangar is the issue is still open to work on

**Comment by shreyamaheshwari1** [comment]
@SaranshBangar if this issue is still open I would like to work on this and would complete it by today.

**Comment by manya1632** [comment]
working Sir 
give me a day or 2

**Comment by manya1632** [comment]
should i proceed with the task ?

**Comment by SupriyaGo** [comment]
Is this issue still available @SaranshBangar ? I can work on it.

**Comment by manya1632** [comment]
![Screenshot 2024-10-25 140346](https://github.com/user-attachments/assets/f081854b-df5d-49f7-baa3-8fefcf234d8f)
The frontend is ready. Backend will be implemented in a day

**Comment by manya1632** [comment]
@SaranshBangar should i just work more on the frontend ( add more pages to get details of the user and authenticate it ) or implement the backend only  for signup and  login page?

**Comment by manya1632** [comment]
I am facing some issue in developing the backend for this particular part, so i'll complete the frontend make a PR .

**Comment by manya1632** [comment]
I have completed my task and raised a PR. Please look at PR #166  !! Let me know if any changes are to be done . Thank You.

**Comment by manya1632** [comment]
Sir please look at the PR and approve further actions

**Comment by manya1632** [comment]
Approved #166
