### ISSUE TITLE
[Feat] Bug & Feature Preset Add

### ISSUE THREAD

**Issue by 4F24L** [SaranshBangar/Daneizo#101]
## BUG & Feature Preset

🟥 There should be an existing form for raising an issue or requesting a feature for your repo.

### Like this : 
![image](https://github.com/user-attachments/assets/4fd801d2-73d3-434f-b3a6-096a30144397)

**Comment by SaranshBangar** [comment]
@4F24L Sure, you can proceed with it. Please remember to -

1. Send a photo here of of the new design before raising a PR
2. Star the repo :)

All the best!
