### ISSUE TITLE
[BUG] Text Unvisible in Top Rented Page

### ISSUE THREAD

**Issue by 4F24L** [SaranshBangar/Daneizo#102]
## Text is not visible in Top-rented page

- Background is black
- Also, texts are in black.

https://github.com/user-attachments/assets/6c15bed5-f5fe-49a3-9a6f-43eb9225d5a7

### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by Arkyapatwa** [comment]
I have raised this issue and got assigned please check the list #92
