### ISSUE TITLE
[BUG] Double Nav Bar in Feature Page 

### ISSUE THREAD

**Issue by 4F24L** [SaranshBangar/Daneizo#103]
## Double nav bar in the feature page

![image](https://github.com/user-attachments/assets/dd546b65-0ccf-4929-baa8-c79d2a863117)

### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by Arkyapatwa** [comment]
I have raised this issue and got assigned please check the list #93
