### ISSUE TITLE
[bug] : Top Reted

### ISSUE THREAD

**Issue by Kuldeepsinghrajpoot** [SaranshBangar/Daneizo#111]
rated items do not show the filter as well and here  need a dynamic routing to make the product details 

![image](https://github.com/user-attachments/assets/3cf0b3f8-5a25-4524-819f-7a8bfc0f0fbf)

**Comment by SaranshBangar** [comment]
@Kuldeepsinghrajpoot You can proceed with it. Please remember to -

1. Send a photo here of of the new design before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!
