### ISSUE TITLE
BUG: Sign In and Sign Up buttons not working

### ISSUE THREAD

**Issue by KhawajaFashi** [SaranshBangar/Daneizo#121]
## Description
Sign In and Sign Up buttons are not working
### Current Behavior:
The Sign in and Sign up buttons on the home page are not working they are not redirecting anywhere.
### Expected Behavior:
The sign-in and sign-up buttons should redirect to the sign-in and sign-up pages respectively. 
## Screenshot:
![image](https://github.com/user-attachments/assets/99235d61-36fa-44d2-9759-50dc2c3c9231)
## Labels:
- Priority: Medium
- Level: 1
- Tags: gssoc-extd, hacktoberfest, hacktoberfest accepted

**Comment by SaranshBangar** [comment]
@KhawajaFashi You can proceed with it. Please remember to -

1. Follow the proper file structure
2. Star the repo :)

All the best!

**Comment by Arkyapatwa** [comment]
Hey @SaranshBangar there already exits an issue regarding this under me #95
