### ISSUE TITLE
BUG: Multiple headers in Features Item and About Us pages

### ISSUE THREAD

**Issue by KhawajaFashi** [SaranshBangar/Daneizo#122]
## Description
Multiple headers in the Features Item and About Us pages make it unusual for the user.
### Current Behavior:
There are two headers one after and another.
### Expected Behavior:
There should be one header that should be working nicely.
## Screenshot:
![image](https://github.com/user-attachments/assets/c15cc2e0-0227-4fd9-8d6f-ff35a9da4c2a)
![image](https://github.com/user-attachments/assets/d4e87b51-b882-465e-b18c-26585971f94d)

## Labels:
- Priority: Medium
- Level: 1
- Tags: gssoc-extd, hacktoberfest, hacktoberfest accepted

**Comment by SaranshBangar** [comment]
@KhawajaFashi Issue already raised #93
