### ISSUE TITLE
BUG: "How it Works" links on Homepage are not visible

### ISSUE THREAD

**Issue by KhawajaFashi** [SaranshBangar/Daneizo#123]
## Description
Home Page "How It Works" links are not visible which may lead to overseen by the user.
### Current Behavior:
The link text is not visible it is black so it camouflages with the background. 
### Expected Behavior:
The link text should be visible it should be white so does not camouflage with the background.
## Screenshot:
![image](https://github.com/user-attachments/assets/29d168da-0096-42b3-b2a1-8041e5592f24)

## Labels:
- Priority: Medium
- Level: 1
- Tags: gssoc-extd, hacktoberfest, hacktoberfest accepted

**Comment by SaranshBangar** [comment]
@KhawajaFashi You can proceed with it. Please remember to -

1. Follow the proper file structure
2. Star the repo :)

All the best!
