### ISSUE TITLE
 Track Rental Dates and History for Users by adding mongoose schema

### ISSUE THREAD

**Issue by IkkiOcean** [SaranshBangar/Daneizo#134]
### Feature Request: Track Rental Dates and History for Users

**Description:**
We need to create the `RentalItem` schema to track rental dates and history for users who rent items. This feature will allow us to manage rental periods, status (e.g., active, completed, overdue), and the total price for each rental.

**Proposed Changes:**
- Add a `rentalHistory` field to the `RentalItem` schema.
- Track individual rentals, including:
  - `renter`: Reference to the user who rented the item.
  - `rentalStartDate`: Date when the rental starts.
  - `rentalEndDate`: Date when the rental ends.
  - `rentalStatus`: Status of the rental (active, completed, overdue).
  - `totalPrice`: The total cost of the rental, calculated based on the duration and price per day.
- Set `available` to `false` when the item is rented, and restore it to `true` once the rental is completed.

#### There is currently no backend template so I will add the template for further backend development also

**Comment by SaranshBangar** [comment]
@IkkiOcean You can proceed with it. Please remember to -

1. Follow the proper file structure
2. Star the repo :)

All the best!
