### ISSUE TITLE
Important updates with the user expereince of the user

### ISSUE THREAD

**Issue by thejatingupta7** [SaranshBangar/Daneizo#14]
I can make the following positive updations to your website:

1. Add a hover colour change on buttons.
![image](https://github.com/user-attachments/assets/3be5a005-0c4a-46e2-8444-9ef4345decf7)

2. Add a mouse depth animation
![image](https://github.com/user-attachments/assets/c8364ca2-f5a4-4d0d-9939-f66b8a6a2694)

3. Slightly increase logo size 
4. 
@SaranshBangar  ,kindly assign this task to me:

**Comment by SaranshBangar** [comment]
@thejatingupta7 sure, go ahead with it, just make sure to -

1. Send a photo here of the final page before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!

**Comment by thejatingupta7** [comment]
You can check this animation and tell me when to ask for PR

https://github.com/user-attachments/assets/799a0673-411c-469a-b3ec-549102f0da3d

**Comment by SaranshBangar** [comment]
@thejatingupta7 The buttons look nice but you should work on revamping the cards

**Comment by thejatingupta7** [comment]
@SaranshBangar 
Below are the updated cards 

https://github.com/user-attachments/assets/4374e65f-a8bf-4448-8a80-909531653d40

And below is the updated favicon image:

![image](https://github.com/user-attachments/assets/ce0c1d8a-b049-4404-8aa4-78c8b251fe9b)

**Comment by SaranshBangar** [comment]
@thejatingupta7 Looks good, please raise the PR

**Comment by SaranshBangar** [comment]
Resolved in #21
