### ISSUE TITLE
Searchbar text overlaps and logs to console

### ISSUE THREAD

**Issue by MihirSaiDudekula** [SaranshBangar/Daneizo#22]
#### Description
When using the search bar, the input text overlaps with 'Toys for children', making it difficult to read. Additionally, the console logs an the character being typed each time the search bar is interacted with(state change).

![image](https://github.com/user-attachments/assets/8acd204b-3a88-442e-9c28-c773022aa566)

#### Steps to Reproduce
1. Navigate to Navbar where the search bar is located.
2. Type onto the search bar when 'Toys for children' is visible.
3. Observe the overlapping text and 
4. open the console to see the output onto the console.

#### Expected Behavior
- The text in the search bar should not overlap with any other elements.
- There should be nothing logged to the console when interacting with the search bar.

#### Actual Behavior
- Text overlaps when typing.
- The search query is logged to the console

**Comment by SaranshBangar** [comment]
![image](https://github.com/user-attachments/assets/9c466693-e51e-43f9-8584-fff56c02c272)

1. The text is not overlapping in my local environment
2. The logging is essential, we will use it to search for products later on

**Comment by MihirSaiDudekula** [comment]
cool, gotcha.
there is overlapping tho, but it's an easy fix.

**Comment by SaranshBangar** [comment]
@MihirSaiDudekula If you want you can raise a PR for the same, we can look at it and see if it is feasible

**Comment by MihirSaiDudekula** [comment]
@SaranshBangar Okay, i'll try to do that.
But tell me more about search functionality.
Which list of items does it need to search actually?

**Comment by SaranshBangar** [comment]
@MihirSaiDudekula It will be used for general search functionality, the users can search items posted by the sellers
