### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [SaranshBangar/Daneizo#25]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by SaranshBangar** [comment]
@Shariq2003 Sure, you can add them after the `Contact` section

**Comment by Shariq2003** [comment]
> @Shariq2003 Sure, you can add them after the `Contact` section. Please remember to -
> 
> 1. Send a photo here of the final look before raising a PR
> 2. Follow the proper file structure
> 3. Star the repo :)
> 
> All the best!

Sure, thanks for assigning
