### ISSUE TITLE
(Simple Feature) (level1) #Add Github Greeting Bot

### ISSUE THREAD

**Issue by KiranBaliga** [SaranshBangar/Daneizo#27]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by SaranshBangar** [comment]
@KiranBaliga I don't think so it is required at this stage, but thank you so much for the kind thoughts!
