### ISSUE TITLE
 Create Login and Registration Pages with Current Design and Color Scheme

### ISSUE THREAD

**Issue by myselfshivams** [SaranshBangar/Daneizo#3]
We need to implement dedicated login and registration pages that match the current design and color scheme of the website. This will enhance the user experience and provide a consistent look and feel across the platform.

Labels:
- GSSoC
- Hacktoberfest

@SaranshBangar Please assign this issue to me(@myselfshivams).

**Comment by SaranshBangar** [comment]
#1 Please do not repeat the issues @myselfshivams
