### ISSUE TITLE
carousel for the user testemonials

### ISSUE THREAD

**Issue by tarunkumar2005** [SaranshBangar/Daneizo#30]
I want to create the carousel for the user testemonials to make the website more dynamic and super awersome to look. 

@SaranshBangar Assign this to me under gssoc 2024 ext and hacktoberfest

**Comment by SaranshBangar** [comment]
@tarunkumar2005 You can proceed with it. Please remember to -

1. Send a photo here of of the new design before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!

**Comment by tarunkumar2005** [comment]
https://github.com/user-attachments/assets/86ce7e16-9f12-436e-891c-74266756ca72

Here is the demo you asked for check it once then i will create the PR for it

**Comment by tarunkumar2005** [comment]
@SaranshBangar

**Comment by SaranshBangar** [comment]
@tarunkumar2005 Looks good, please raise a PR for the same

**Comment by tarunkumar2005** [comment]
@SaranshBangar Done
