### ISSUE TITLE
create a top rented page 

### ISSUE THREAD

**Issue by ShivanshPlays** [SaranshBangar/Daneizo#32]
I can create a top rented page where the most rented products are displayed.
The items will be hardcoded for now as there is no backend to this project....
![Screenshot 2024-10-06 195252](https://github.com/user-attachments/assets/ea16ad6f-f36b-440b-b130-8529d14590f8)

Please assign me this issue under level2 gssoc gssoc-ext hacktoberfest hacktoberfest-accepted...I'll be happy to work on it 💯

PS: I have thoroughly visited all prs and issues assigned and I saw that there is already a backend PR (#18), 
when that is merged, 
I can raise another issue for the same top rented page and implement it fully along with the necessary changes in the backend, like schema and logic for calculating top rated products.

**Comment by SaranshBangar** [comment]
@ShivanshPlays You can proceed with it. Please remember to -

1. Send a photo here of of the new design before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!

**Comment by ShivanshPlays** [comment]
![image](https://github.com/user-attachments/assets/750033d9-39fc-48a0-8791-2325af241c67)

**Comment by ShivanshPlays** [comment]
Okay I'll raise the PR by EOD

**Comment by ShivanshPlays** [comment]
ANY ISSUE? @SaranshBangar

**Comment by SaranshBangar** [comment]
@ShivanshPlays I have written the issue in the review of your PR
