### ISSUE TITLE
Implement Missing Meta Tags for SEO Improvement

### ISSUE THREAD

**Issue by myselfshivams** [SaranshBangar/Daneizo#4]
The current website is missing several crucial meta tags that are essential for search engine optimization (SEO). To enhance the site's visibility and ranking on search engines, we need to add the following meta tags:

- Title tags
- Description tags
- Keywords tags
- Open Graph tags for social media sharing
- Robots meta tag

Labels:
- GSSoC
- Hacktoberfest

@SaranshBangar Please assign this issue to me(@myselfshivams).

**Comment by SaranshBangar** [comment]
@myselfshivams Go ahead!

**Comment by SaranshBangar** [comment]
Resolved in #5
