### ISSUE TITLE
[BUG] Login / Register Page 404 

### ISSUE THREAD

**Issue by 4F24L** [SaranshBangar/Daneizo#42]
## Register Page 404 Not found
- https://daneizo.vercel.app/register

![image](https://github.com/user-attachments/assets/8c21610d-3ae2-410a-a37a-2ca0fc7a5421)

**Comment by SaranshBangar** [comment]
@4F24L You can proceed with it. Please remember to -

1. Send a photo here of of the new design before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!

**Comment by 4F24L** [comment]
https://github.com/user-attachments/assets/1fc5e087-b239-46cb-b014-d43b1fe900be

Started fixing it !!
