### ISSUE TITLE
[BUG] Landing Page Overflow

### ISSUE THREAD

**Issue by 4F24L** [SaranshBangar/Daneizo#44]
## Landing Page Overflow Issue
- Homepage shouldn't have any overflow.
- Nav bar links isn't working.

https://github.com/user-attachments/assets/eb6bac22-460d-467f-8d26-bec9aa7ded65

**Comment by SaranshBangar** [comment]
@4F24L Sure, please follow the guidelines mentioned in #42

**Comment by 4F24L** [comment]
![image](https://github.com/user-attachments/assets/95bdf2c5-353a-4b86-a2cd-abf34c32c078)


### This PR will fix this
