### ISSUE TITLE
Implementing Admin Panel

### ISSUE THREAD

**Issue by 0vai5** [SaranshBangar/Daneizo#46]
The creation of admin panel will make the data more dynamic and help the admin to apply all CRUD application related to the user, the rental data related to it,
Moreover it will be made in nextJS itself so it will be utilising the features of NextJS more efficiently 
Please assign this task to me.
And label this as Gssoc-ext

@SaranshBangar

**Comment by SaranshBangar** [comment]
@0vai5 You can proceed with it. Please remember to -

1. Send a photo here of of the new design before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!

**Comment by 0vai5** [comment]
Hey @SaranshBangar, 

After reviewing the requirements, I believe an admin panel isn't necessary, as the project mainly needs a backend to handle user data, posts, and a functional registration and authorization system. Let me know if I can proceed with implementing the backend.
