### ISSUE TITLE
Redesiging the About Page

### ISSUE THREAD

**Issue by Hh440** [SaranshBangar/Daneizo#53]
I would like to request the assignment of Redesiging the About page for our website. This page will provide users with an overview of our features and future vision.

Key points to cover:
- Mission: A brief description of what our website aims to achieve.
- Key Features: A summary of the main functionalities we offer.
- User Benefits: How our platform helps and supports users.
- Technologies: Highlighting the technology stack we use.
- Security & Privacy: Information on how we ensure user data is safe.
- Future Insights: A glimpse of upcoming features and plans for the platform.
![Screenshot from 2024-10-09 19-09-50](https://github.com/user-attachments/assets/4bc8092f-06b2-4058-adf7-a6b34d5bd428)

**Comment by SaranshBangar** [comment]
@Hh440 The current About page is fine, we first need to make the website functional and then worry about how to make it look better 👍🏼
