### ISSUE TITLE
OverFlow of Testimonials cards

### ISSUE THREAD

**Issue by ShivanshPlays** [SaranshBangar/Daneizo#55]
https://github.com/user-attachments/assets/f404174a-e6d3-40d1-bc06-b17be49a1a5a

**Comment by SaranshBangar** [comment]
@ShivanshPlays You can proceed with it. Please remember to -

1. Send a photo here of of the new design before raising a PR
2. Follow the proper file structure
3. Star the repo :)
4. 
All the best!
