### ISSUE TITLE
Auto Commenting On New issue Creation

### ISSUE THREAD

**Issue by sejals23** [SaranshBangar/Daneizo#57]
It ensures that comments on issues follow a consistent format or structure. This helps teams maintain a standardized approach to handling issues, reducing confusion and misunderstandings.
Users don’t need to manually add repetitive information or instructions. The automatic comment can include standard guidelines, troubleshooting steps, or links to documentation.

**Comment by SaranshBangar** [comment]
@sejals23 I don't think so it is required at this moment but thank you for bringing it to our notice!
