### ISSUE TITLE
Create Custom 404 Page with Current Style and Color Scheme

### ISSUE THREAD

**Issue by myselfshivams** [SaranshBangar/Daneizo#6]
Currently, the website lacks a custom 404 error page, which can lead to a poor user experience when users encounter broken links or unavailable content. We need to design and implement a custom 404 page that aligns with the existing UI style and colour scheme of the website.

Labels:
- GSSoC
- Hacktoberfest

@SaranshBangar Please assign this issue to me(@myselfshivams).

**Comment by SaranshBangar** [comment]
@myselfshivams Alright, you can start on this issue!

**Comment by SaranshBangar** [comment]
Resolved in #10
