### ISSUE TITLE
Modification of README.md file, & Creation of dedicated Contributing.md file and LICENSE.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [SaranshBangar/Daneizo#67]
### 1) Add animated line separators and add GSSoC 2024 Extended accepted banner
I want to add animated line separators in the README.md file to make it look more attractive and readable. I would also like to add the GSSoC 2024 Extended accepted image for Contributors to know that this repository is officially accepted for GSSoC contribution.
![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Replace the Contact section  with a **Team section**
The present Contact section in the **README.md** file is not looking attractive:
![image](https://github.com/user-attachments/assets/4923d6fe-50fe-4ea3-a7f6-f93caa546b76)

The Team section will look more organized and readable and let the Contributors know whom to contact if they face any issues.

![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors.
![image](https://github.com/user-attachments/assets/602470c5-1198-44d3-b86d-df0479f032be)

I would like to update it and try to automate the process.
![image](https://github.com/user-attachments/assets/d9e9ab50-3967-420b-a948-aa6e2baf826d)

## 2. Add a dedicated Contributing.md
A dedicated file for contributors to refer to and understand where to begin with. Merging the README.md with the Contributing section reflects poor documentation style. I will provide a brief idea about the contribution in the **README.md** file and provide a redirect to the newly made **Contributing.md** file for contributors to refer to.
I would also add a redirect to **Contributing.md** from **README.md**

Reference file image:
![image](https://github.com/user-attachments/assets/274556d1-6f47-43eb-9e22-a0b6986f3c8f)
![image](https://github.com/user-attachments/assets/c59801df-632e-4966-b05d-e36c0234e338)
![image](https://github.com/user-attachments/assets/dd772221-db42-416c-8398-389677255c63)

## 3. Add MIT LICENSE
The MIT LICENSE is missing in your project:
![image](https://github.com/user-attachments/assets/bd5e4b74-24f7-4d02-b3b1-763f0e0a3a72)

The presence of a **LICENSE** file explicitly states the terms under which the code can be used, modified, and shared. If a project does not have a **LICENSE** file, it implies that the author has not granted any rights to others, and legally, no one has permission to use, distribute, or modify the code.
So, adding a LICENSE file is a best practice for open-source projects.
![image](https://github.com/user-attachments/assets/17e527af-96ab-4a68-925d-1e417a38e636)

I would like to work on the issues so that I can contribute to making the repository more accessible and friendly for other Contributors.
Please assign this issue to me under level3, gssoc-ext and hacktoberfest-accepted(if available) labels.

**Comment by SaranshBangar** [comment]
@rajdeepchakraborty-rc, Sure please go ahead with this task, unfortunately I can only assign it `Level 2` instead of `Level 3`

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc, Sure please go ahead with this task, unfortunately I can only assign it `Level 2` instead of `Level 3`

That's fine! Thanks for assigning the issue to me. I have a few pending issues assigned to me and will start working on this issue soon after I am done with them.

**Comment by rajdeepchakraborty-rc** [comment]
I will provide you updates about the work and also ask any queries in this chat too

**Comment by SaranshBangar** [comment]
@rajdeepchakraborty-rc Sure 👍🏼

**Comment by rajdeepchakraborty-rc** [comment]
@SaranshBangar I wanted to update you regarding the work progress.

**Comment by rajdeepchakraborty-rc** [comment]
I have added the MIT License to your project:
![image](https://github.com/user-attachments/assets/4e9d63fc-255b-4918-9ac0-2a30a3d6b909)

**Comment by rajdeepchakraborty-rc** [comment]
I modified the Contribution Guide section:

- Before
![image](https://github.com/user-attachments/assets/38793505-6f68-4533-b808-1f4f23441a0f)

- After
![image](https://github.com/user-attachments/assets/e6a23992-10f1-40f6-a9e5-0396597f53e1)
![image](https://github.com/user-attachments/assets/9b311929-a7e4-49aa-a615-e0b723cbabb1)

Also added a redirect to the Contributing.md file from the README.md file:
![image](https://github.com/user-attachments/assets/5a4fe18a-817d-4d94-8d53-69bffb1860d5)

**Comment by rajdeepchakraborty-rc** [comment]
This is the newly added **Contribution.md** file that I have created:
![image](https://github.com/user-attachments/assets/5aff41b9-bd41-4a4c-bc09-04475480659f)
![image](https://github.com/user-attachments/assets/b9ac8bc3-826f-4f73-befc-7965aba94dae)
![image](https://github.com/user-attachments/assets/920d8a9b-c8de-4b5c-b03d-bb1be2d7792c)
![image](https://github.com/user-attachments/assets/f72bd69c-2888-49b5-9854-315d17b0c64d)

**Comment by rajdeepchakraborty-rc** [comment]
This is the new **Team Section** that I have added:

- Before
![image](https://github.com/user-attachments/assets/6c299747-f42b-428d-a547-0ca2dec3c9d9)

- After
![image](https://github.com/user-attachments/assets/72c7d40b-e94d-4dfc-9650-3bf56eba4f5e)

**Comment by rajdeepchakraborty-rc** [comment]
Here is a video showing the changes done:

https://github.com/user-attachments/assets/9608875d-1369-4874-9d19-fadda5d7b765

Let me know if you want any changes or something that I should add.

**Comment by SaranshBangar** [comment]
Resolved in #84
