### ISSUE TITLE
Implementing scroll to top feature

### ISSUE THREAD

**Issue by AswaniBolisetti** [SaranshBangar/Daneizo#69]
@SaranshBangar I would like to add the scroll to top feature, could you please assign me this under gssoc-ext, hacktoberfest-accepted and level2

**Comment by SaranshBangar** [comment]
@AswaniBolisetti Sure, you can add them after the Contact section. Please remember to -

1. Send a photo here of the final look before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!
