### ISSUE TITLE
Create About Us page

### ISSUE THREAD

**Issue by Itachii27** [SaranshBangar/Daneizo#7]
Currently the website doesn't have any " About us" page but it has been added in the drop down which redirects to 404.

I want to work on this issue. Please assign this issue to me under gssoc-extd, hacktoberfest, hacktoberfest-accepted.

**Comment by SaranshBangar** [comment]
Sure @Itachii27 you can work on this issue, just make sure to -
1. Send a photo here of the final page before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!

**Comment by Itachii27** [comment]
Hi @SaranshBangar I have done. Below is the image for same:
![image](https://github.com/user-attachments/assets/ce368d11-f887-4810-9db8-3e72c9947c03)
Kindly let me know if require any changes.

**Comment by SaranshBangar** [comment]
It looks good, just use the font that is being used in the home page

**Comment by Itachii27** [comment]
Hi @SaranshBangar I have done changes. Kindly review the PR

**Comment by SaranshBangar** [comment]
Resolved in #15
