### ISSUE TITLE
Issue Title: "Add Cursor-Following Animation"

### ISSUE THREAD

**Issue by AswaniBolisetti** [SaranshBangar/Daneizo#70]
@SaranshBangar 
Issue Description: The website currently lacks interactive design elements that enhance user experience. I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.

I’d like to work on adding this feature. Please assign this issue to me under gssoc-ext, hacktoberfest-accepted, level2

**Comment by SaranshBangar** [comment]
@AswaniBolisetti I don't think so it is required at this stage. Please refer to issue #2
