### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [SaranshBangar/Daneizo#76]
Adding the contributors page to mention all the awersome people who have contributed to the website.

@SaranshBangar Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by SaranshBangar** [comment]
@tarunkumar2005 Sure, you can add them. Please remember to -

1. Send a photo here of the final look before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!

**Comment by tarunkumar2005** [comment]
Here is the image bro is it good or any changes you want :- 

![screencapture-localhost-3000-contributor-2024-10-13-23_28_21](https://github.com/user-attachments/assets/ebb4eada-6a8e-4965-bc6a-aa8d38647ca8)

@SaranshBangar Can i raise the PR if you like this

**Comment by tarunkumar2005** [comment]
@SaranshBangar Can i raise the PR (reminder)

**Comment by SaranshBangar** [comment]
@tarunkumar2005 Sure, please raise the PR
