### ISSUE TITLE
Fix the Navbar

### ISSUE THREAD

**Issue by Itachii27** [SaranshBangar/Daneizo#8]
Currently the navbar is not structured. 
![image](https://github.com/user-attachments/assets/ee51ab97-0f1e-4fb3-99ab-79dcef71a7d7)

I would like to to work on this issue. Kindly assign this issue to me under gssoc-extd, hacktoberfest, hacktoberfest-accepted

**Comment by Itachii27** [comment]
Hi @SaranshBangar I have done changes. Below is the screenshot
![image](https://github.com/user-attachments/assets/10d45b76-5187-4c67-843e-72976c0c3d50)
The user would have option to toggle between **Go to Register** or **Go to Login** Page
As most of pages are not yet made ( eg. Login page, Register page etc) the functionality is still same of this navbar. I worked on the CSS part only.
Let me know if any changes required.

**Comment by SaranshBangar** [comment]
@Itachii27 It looks good but please change "Go to Register" and write "Login/Register", then you can raise the PR
