### ISSUE TITLE
Build a contact us page with backend 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [SaranshBangar/Daneizo#82]
I can make it with all funcanility and also handle the form submissions on backend

Please assign me with level 3 tags under gssocext

**Comment by SaranshBangar** [comment]
@Sawan-Kushwah Sure, please follow the rules from #81

**Comment by Sawan-Kushwah** [comment]
![Screenshot 2024-10-16 000426](https://github.com/user-attachments/assets/b1f98ec6-81fd-4512-9249-548c04222a16)
This is the UI of contact form 

![Screenshot 2024-10-16 000656](https://github.com/user-attachments/assets/d30c9d58-b32c-4306-9333-b45ced3af59c)
This is how data is saved on MongoDB database 


![image](https://github.com/user-attachments/assets/33ff1d08-6658-4dbf-bf1f-fe50d5aa66ef)

this is the file structure 
UI is under contact folder 

backend api is ander 
api > contact > route.js

Created a fully functional contact form where you will receive the data on database also maintained the file structure

**Comment by Sawan-Kushwah** [comment]
@SaranshBangar Can i make PR?

**Comment by SaranshBangar** [comment]
@Sawan-Kushwah Sure, go ahead 👍🏼

**Comment by Sawan-Kushwah** [comment]
@SaranshBangar can I get level 3 for this pull request as I have implemented front-end backend and database of contact form with proper folder structure it's a kind request to u ☺️
