### ISSUE TITLE
Addition of BackToTop Button Feature in UI 

### ISSUE THREAD

**Issue by Shariq2003** [SaranshBangar/Daneizo#88]
Enhance the User Experience By Providing One-Click Smooth Scrolling To Top.

![image](https://github.com/user-attachments/assets/3360576b-8829-424b-80d9-194d3d312625)

Like this, Upward Arrow

@SaranshBangar please assign this to me.

**Comment by SaranshBangar** [comment]
@Shariq2003 You can proceed with it. Please remember to -

1. Send a photo here of of the new design before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!
