### ISSUE TITLE
The footer is not good 

### ISSUE THREAD

**Issue by jayanththalla** [SaranshBangar/Daneizo#9]
By adding the title and icon and social media 
![image](https://github.com/user-attachments/assets/a3908ae1-57d9-43cb-b88e-0ed7b323ca0b)

**Comment by SaranshBangar** [comment]
Sure, you can work on this @jayanththalla, just make sure to -

1. Send a photo here of the final page before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!

**Comment by jayanththalla** [comment]
please label under the hacktoberfest also

**Comment by SaranshBangar** [comment]
That is not necessary since the repo has the `hacktoberfest` tag

![image](https://github.com/user-attachments/assets/51757746-b80a-470d-aa5d-e32f2378bd85)

**Comment by SaranshBangar** [comment]
Resolved in #16
