### ISSUE TITLE
Redesigning of Login/SignUp Page that match with the Webapp Theme

### ISSUE THREAD

**Issue by Shariq2003** [SaranshBangar/Daneizo#90]
I want to enhance the Login and Signup Page by Redesigning both, in the web app.

![image](https://github.com/user-attachments/assets/97b32873-4178-4378-aa9f-bff5430de59a)

This looks so weird

@SaranshBangar Please assign this to me.

**Comment by SaranshBangar** [comment]
@Shariq2003 This issue is already raised in #77
