### ISSUE TITLE
Newsletter Implementation | Email Validation | Toast Alerts Addition 

### ISSUE THREAD

**Issue by Shariq2003** [SaranshBangar/Daneizo#91]
I want to add the following features :-

1. Newsletter Implementation
2. Email Validation
3. Toast Alerts Addition 

https://github.com/user-attachments/assets/3eb4ff87-b6f7-429b-9105-911856c1c99e

@SaranshBangar Please assign this to me

**Comment by Shariq2003** [comment]
Please increase the level

**Comment by SaranshBangar** [comment]
@Shariq2003 I am sorry, this issue is very basic and can be resolved easily

**Comment by Shariq2003** [comment]
But the Progress Issue should be of Level 2

**Comment by SaranshBangar** [comment]
@Shariq2003 That is great but just changing the type of an `input` tag cannot be considered for `level 2` in my repo

**Comment by Shariq2003** [comment]
> @Shariq2003 That is great but just changing the type of an `input` tag cannot be considered for `level 2` in my repo

I am also implementing react toats sir

**Comment by SaranshBangar** [comment]
@Shariq2003 Please raise the PR for the same, I will review it and verify the level then

**Comment by Shariq2003** [comment]
> @Shariq2003 Please raise the PR for the same, I will review it and verify the level then

Review my PR sir
