### ISSUE TITLE
UI Bug/Issue Fonts not visible 

### ISSUE THREAD

**Issue by Arkyapatwa** [SaranshBangar/Daneizo#92]
UI Bug - The font colors in Top Rented items page are unrecognizable/not visible colors.

https://github.com/user-attachments/assets/fd604f38-bf5b-4010-a3b6-b67bea15e7c1

Please add hacktoberfest and GSSoC24 tag and Assign this Issue to me.

**Comment by Arkyapatwa** [comment]
Hey @SaranshBangar check this. I have corrected the fonts UI. If you approve this I can raise a PR for this issue.
![image](https://github.com/user-attachments/assets/499f2b00-8819-4aa6-8dfe-d0c6b70579c5)

**Comment by SaranshBangar** [comment]
Resolved in PR #107
