### ISSUE TITLE
Presence of Double Nav bar in About Section

### ISSUE THREAD

**Issue by kottarivaibhav** [SaranshBangar/Daneizo#99]
I just went to the about section of the web page and found that there is a presence of double Header/Navbar in this column . I would like to tackle this Lvl-1 issue 

Screenshot of the issue:
![image](https://github.com/user-attachments/assets/d7ed0ea9-280f-4b68-9bfc-be1ef678d6b3)

I would like to be assigned under gssoc-24 ext and hactoberfest .
Thank you

**Comment by SaranshBangar** [comment]
@kottarivaibhav This issue is already raised, please check issue #93
